### ISSUE TITLE
AZ NLP Corpus in one file

### ISSUE THREAD

**Issue by Kreeby** [raminrahimzada/az-corpus-nlp#1]
Dear Ramin,

I am wondering whether you have this corpus in one file? We just wanted to use it in our diploma work and we need huge data. Just needed to remove symbols, digits and other stuff in order to apply word embedding algos to corpus

Thanks!

**Comment by raminrahimzada** [comment]
Hi, I will have some problems about github storage, bcs of overflow of its file size limit

So if You need all files together we can provide small tool to combine all files 
 
And one more disclose about repo files is that some files may contain nonsense data bcs of pdf parser issues( I gathered these files as the result of parsing text from pdfs)
So i suggest you that check all files by hand to make your diploma work best

**Comment by Kreeby** [comment]
> Hi, I will have some problems about github storage, bcs of overflow of its file size limit
> 
> So if You need all files together we can provide small tool to combine all files
> 
> And one more disclose about repo files is that some files may contain nonsense data bcs of pdf parser issues( I gathered these files as the result of parsing text from pdfs)
> So i suggest you that check all files by hand to make your diploma work best

Would be perfect if you can provide that tool, and thanks a lot for making clear about the data.

My gmail: rashad.naghiyev@gmail.com

**Comment by raminrahimzada** [comment]
Here is the c# code [gist](https://gist.github.com/raminrahimzada/5168361571b72ebf1eb861e6625c5c44) to  join all files

You are welcome
